#ifndef SCHITEMINPUT_GLOBAL_H
#define SCHITEMINPUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCHITEMINPUT_LIBRARY)
#  define SCHITEMINPUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCHITEMINPUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCHITEMINPUT_GLOBAL_H
