#ifndef COMMITINFO_GLOBAL_H
#define COMMITINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMITINFO_LIBRARY)
#  define COMMITINFOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMITINFOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMITINFO_GLOBAL_H
