#ifndef IREPOSITORYFACTROY_GLOBAL_H
#define IREPOSITORYFACTROY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IREPOSITORYFACTROY_LIBRARY)
#  define IREPOSITORYFACTROYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IREPOSITORYFACTROYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IREPOSITORYFACTROY_GLOBAL_H
