ENUM_ELEMENT( SE3_NO_ERROR,           0, QT_TRANSLATE_NOOP("Errors", "No error")),
ENUM_ELEMENT( USER_ERROR,             -1, QT_TRANSLATE_NOOP("Errors", "User error")),
ENUM_ELEMENT( UNKNOWN_ERROR,          -2, QT_TRANSLATE_NOOP("Errors", "Unknown error")),
ENUM_ELEMENT( MAIN_PDIR_MISS,         -20, QT_TRANSLATE_NOOP("Errors", "Plugin`s directory not exist")),
ENUM_ELEMENT( MAIN_LDIR_MISS,         -21, QT_TRANSLATE_NOOP("Errors", "Lib's directory not exist")),
ENUM_ELEMENT( MAIN_PCOPY_ERR,         -22, QT_TRANSLATE_NOOP("Errors", "Can't copy plugin from storage")),
ENUM_ELEMENT( MAIN_LCOPY_ERR,         -23, QT_TRANSLATE_NOOP("Errors", "Can't copy library from storage")),
ENUM_ELEMENT( UPD_DBFILE_MISS,        -24, QT_TRANSLATE_NOOP("Errors", "Can't open file for parsing update information")),
ENUM_ELEMENT( BCK_ADDPATH_EMPTY,      -25, QT_TRANSLATE_NOOP("Errors", "Backuping file path is empty")),
ENUM_ELEMENT( BCK_ADDPATH_DBL,        -26, QT_TRANSLATE_NOOP("Errors", "Backuping file has already been added")),
ENUM_ELEMENT( BCK_CREATE_DIR_ERR,     -27, QT_TRANSLATE_NOOP("Errors", "Create backup directory is failed")),
ENUM_ELEMENT( UPD_FILE_NONEED,        -28, QT_TRANSLATE_NOOP("Errors", "No update for requested file")),
